# Generated by Django 4.0.7 on 2022-11-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrator', models.CharField(max_length=150)),
                ('currency', models.CharField(max_length=150)),
                ('purpose', models.CharField(max_length=150)),
                ('what', models.CharField(max_length=150)),
                ('license', models.CharField(max_length=150)),
                ('value', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='value_set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrator', models.CharField(max_length=150)),
                ('currency', models.CharField(max_length=150)),
                ('purpose', models.CharField(max_length=150)),
                ('what', models.CharField(max_length=150)),
                ('license', models.CharField(max_length=150)),
                ('value', models.CharField(max_length=150)),
            ],
        ),
    ]
