# Generated by Django 4.0.7 on 2022-11-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='r_w',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150)),
                ('generate_id', models.IntegerField()),
            ],
        ),
    ]
