# Generated by Django 4.0.7 on 2022-11-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administator', '0002_r_w'),
    ]

    operations = [
        migrations.CreateModel(
            name='donor_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150)),
                ('donor_id', models.IntegerField()),
            ],
        ),
    ]
