# Generated by Django 4.0.7 on 2022-11-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administator', '0003_donor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor_id',
            name='donor_id',
            field=models.CharField(max_length=150),
        ),
    ]
