# Generated by Django 4.0.7 on 2022-11-23 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administator', '0004_alter_donor_id_donor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor_id',
            old_name='donor_id',
            new_name='id_donor',
        ),
    ]
