# Generated by Django 4.0.7 on 2022-11-23 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administator', '0005_rename_donor_id_donor_id_id_donor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='donor_id',
            new_name='donor_id_generate',
        ),
    ]
