# Generated by Django 4.0.2 on 2022-11-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='yourname',
            field=models.CharField(default='exit', max_length=150),
            preserve_default=False,
        ),
    ]
