# Generated by Django 4.0.2 on 2022-11-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_yourname'),
    ]

    operations = [
        migrations.CreateModel(
            name='purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourname', models.CharField(max_length=150)),
                ('organisation', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=150)),
                ('purpose', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
