# Generated by Django 4.0.2 on 2022-11-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_client_purpose_delete_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('type', models.CharField(max_length=150)),
                ('targetamount', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='files')),
            ],
        ),
    ]
