# Generated by Django 4.0.2 on 2022-11-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='employers',
            field=models.CharField(default='exit', max_length=150),
            preserve_default=False,
        ),
    ]
