# Generated by Django 4.0.2 on 2022-11-18 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_requirement_employers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirement',
            old_name='type',
            new_name='buisness',
        ),
    ]
