# Generated by Django 4.0.2 on 2022-11-18 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_rename_type_requirement_buisness'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='requirement',
            new_name='money',
        ),
    ]
