# Generated by Django 4.0.7 on 2022-11-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_link_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='link_amount',
            name='email',
            field=models.EmailField(default='exit', max_length=150),
            preserve_default=False,
        ),
    ]
