# Generated by Django 4.0.7 on 2022-11-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_link_amount_targetamount1'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_purpose',
            name='booleann',
            field=models.BooleanField(default=False),
        ),
    ]
