# Generated by Django 4.0.7 on 2022-11-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donar', '0003_tax_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='reciptient_amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=150)),
                ('recipitent', models.CharField(max_length=150)),
            ],
        ),
    ]
