# Generated by Django 4.0.7 on 2022-11-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donar', '0005_donor_link_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciptient_amount',
            name='name',
            field=models.CharField(default='exit', max_length=150),
            preserve_default=False,
        ),
    ]
