# Generated by Django 4.0.7 on 2022-11-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donar', '0006_reciptient_amount_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor_link_amount',
            name='update',
            field=models.BooleanField(default=False),
        ),
    ]
