# Generated by Django 4.0.7 on 2022-11-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donar', '0007_donor_link_amount_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciptient_amount',
            name='update',
            field=models.BooleanField(default=False),
        ),
    ]
