# Generated by Django 4.0.7 on 2022-11-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donar', '0008_reciptient_amount_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciptient_amount',
            name='ecrypt',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
