# Generated by Django 4.0.7 on 2022-11-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donar', '0009_reciptient_amount_ecrypt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciptient_amount',
            name='amount',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='reciptient_amount',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='reciptient_amount',
            name='recipitent',
            field=models.CharField(max_length=500),
        ),
    ]
