# Generated by Django 4.0.7 on 2022-11-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donar', '0010_alter_reciptient_amount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciptient_amount',
            name='ecrypt',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
