# Generated by Django 4.0.7 on 2022-11-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donar', '0011_alter_reciptient_amount_ecrypt'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor_purpose',
            name='b3',
            field=models.BooleanField(default=False),
        ),
    ]
