# Generated by Django 4.0.7 on 2022-11-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donar', '0012_donor_purpose_b3'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciptient_amount',
            name='b5',
            field=models.BooleanField(default=False),
        ),
    ]
