# Generated by Django 4.0.7 on 2022-11-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='wallet_entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=150)),
                ('purpose', models.CharField(max_length=150)),
            ],
        ),
    ]
