# Generated by Django 4.0.7 on 2022-11-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0002_wallet_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet_entry',
            name='teamname',
            field=models.EmailField(max_length=150),
        ),
    ]
