# Generated by Django 4.0.7 on 2022-11-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0003_alter_wallet_entry_teamname'),
    ]

    operations = [
        migrations.AddField(
            model_name='technical',
            name='bt',
            field=models.BooleanField(default=False),
        ),
    ]
