# Generated by Django 4.0.7 on 2022-11-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0004_technical_bt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technical',
            name='bt',
        ),
        migrations.AddField(
            model_name='wallet_entry',
            name='bt',
            field=models.BooleanField(default=False),
        ),
    ]
